name: ${project.name}
main: ws.mcserver.in.mostlynorefunds.MostlyNoRefunds
version: ${project.version}
authors: [Username4723]
api-version: ${project.apiversion}
commands:
  refund:
    description: Refund an inventory to a player
    usage: /refund <Player> <Death ID>

permissions:
  mostlynorefunds.refund:
    description: Refund a user's items
    default: op