name: MostlyNoRefunds
main: ws.mcserver.in.mostlynorefunds.MostlyNoRefunds
version: ${project.version}
authors: [HelloWorld]
api-version: "1.13"
commands:
  refund:
    description: Refund an inventory to a player
    usage: /refund <Player> <Death ID>

permissions:
  mostlynorefunds.refund:
    description: Refund a user's items
    default: op